### ISSUE TITLE
Support for Immersive Engineerings Excavator

### ISSUE THREAD

**Issue by Gitcrafter** [Srdjan-V/TweakedExcavation#1]
Hello, can you make a mod to add craftweaker support for Immersive Engineerings Minerals in a similar way as you have for Immersive Petroleums Reservoirs, with custom powertiers, JEI-support and specificly using the IItemStack: <minecraft:iron_ore> or IOreDictEntry: <ore:oreIron> to specify the results instead of a string[]: ["oreIron"], wich limits the results to things, that have an oredict-tag, that their own support uses

**Comment by Srdjan-V** [comment]
I will look into that and see what I can do, as I have not looked at IE's code for the excavator.

**Comment by Gitcrafter** [comment]
I didn´t expexted such a fast reply and thanks for looking into it

**Comment by Srdjan-V** [comment]
So i have looked into IE:
1: I can probably add power tiers
2: Why do you want to use `IItemStack: minecraft:iron_ore or IOreDictEntry: ore:oreIron`, you can specify preferred mod ores within the [configs](https://github.com/BluSunrize/ImmersiveEngineering/blob/d5a9ad5e13be61f9b9587c647e6e36d4113eef00/src/main/java/blusunrize/immersiveengineering/common/Config.java#L95), if you want to excavate bloks like stone or dirt that's a diffident thing

**Comment by Gitcrafter** [comment]
to 1: sounds great,
to 2: well thats exactly, what I want to do, for example I want to add a mineral, that is exklusive to the Betweenlands and yields Betweenlands Silt and Mud, which in Silts case would normally force me to use ["sand"] which may result in Silt being picked as the mined Block or it may use any of the other 5+ blocks oredicted as "sand", so I would get around that bei using <thebetweenlands:silt> and in the case of Mud would be impossible as Mud doesn´t has an oredict-tag, and that is just the first example, that I remember trying,
can you do the JEI-support?

**Comment by Srdjan-V** [comment]
I will see what i can do, but dont expect it to be soon.

**Comment by Gitcrafter** [comment]
Thank you and keep up the good work

**Comment by Srdjan-V** [comment]
> can you do the JEI-support?

Yes i will be adding that

**Comment by Gitcrafter** [comment]
I´m waiting in anticipation

**Comment by Srdjan-V** [comment]
Download this file and see if it works with your needs. I have tested it with vanilla bloks only. HEI/JEi will come later

[Test not final.zip](https://github.com/Srdjan-V/TweakedExcavation/files/9627478/Test.not.final.zip)

**Comment by Gitcrafter** [comment]
When trying to test it, the game says, that tweakedlib is missing, despite it being in the modfolder:

![2022-09-23_15 15 21](https://user-images.githubusercontent.com/81863925/191968921-1bf36264-f3de-49c3-b2a7-df7de062d934.png)

**Comment by Srdjan-V** [comment]
[Fixed TL detection.zip](https://github.com/Srdjan-V/TweakedExcavation/files/9634340/Fixed.TL.detection.zip)

**Comment by Gitcrafter** [comment]
It works now, combining the oredict with the mod, you want the block from, works fine, but what about blocks, that don´t have an oredict, like mud?(see the below Screenshot), also will you add a Dimension Whitelist?(I forgot to mention that in the initial post)

Apart from the Mud-problem and the missing Dimension-Whitelist, it is already very good.

 ![2022-09-23_18 04 27](https://user-images.githubusercontent.com/81863925/192004183-6936130b-ca49-4395-8c0a-39c2dfb47978.png)

**Comment by Srdjan-V** [comment]
> also will you add a Dimension Whitelist

As far as i understand IE already supports a [whitelist](https://github.com/BluSunrize/ImmersiveEngineering/blob/d5a9ad5e13be61f9b9587c647e6e36d4113eef00/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/Excavator.java#L62), you just cant register a blacklist and a whitelist at the same time. I cant say if it would work without some rewrites

>but what about blocks, that don´t have an oredict, like mud

Im not sure how blocks are registered within the game, but i will see what i can do

**Comment by Srdjan-V** [comment]
You can add custom blocks, and blocks with metadata.

[Test2.zip](https://github.com/Srdjan-V/TweakedExcavation/files/9636755/Test2.zip)

**Comment by Gitcrafter** [comment]
You solved the Mud-problem, thats great and about the black-/whitelist, mabye setting it with a true/false value?(true makes it a whitelist/false a blacklist) I don´t have any idea how programming works so that´s all I can think of.

**Comment by Srdjan-V** [comment]
>black-/whitelist, mabye setting it with a true/false value?(true makes it a whitelist/false a blacklist)

This is allready a [thing](https://docs.blamejared.com/1.12/en/Mods/Immersive_Engineering/CraftTweaker_Support/Excavator/Excavator#example)

**Comment by Gitcrafter** [comment]
Well then why not keep it that way, if it is to complicated to change it?

**Comment by Srdjan-V** [comment]
This build includes JEI support, and blacklist and whitelist support. But i would ask you to test it, code wise it should work
[test3.zip](https://github.com/Srdjan-V/TweakedExcavation/files/9641431/test3.zip)

**Comment by Gitcrafter** [comment]
It works and it is already perfect, aside from some polishing, like bringing the powertier-/dimensionlist-infos inline with those from Tweakedpetroleum and I think the tooltip thats telling the ore-chances schould say chance without the "s"

**Comment by Srdjan-V** [comment]
Go ahead and test this build
[Test 4.zip](https://github.com/Srdjan-V/TweakedExcavation/files/9700585/Test.4.zip)

If you have time also test these zen [methods](https://github.com/Srdjan-V/TweakedExcavation/blob/master/src/main/java/srki2k/tweakedexcavation/common/compat/crafttweaker/TweakedExcavator.java)

**Comment by Gitcrafter** [comment]
One thing thats still missing, is the Mineral Spawn Weight info

**Comment by Gitcrafter** [comment]
It´s working beautifully, I have to thank you a lot.
